baseURL = "https://zhongxiangzhou.com/"
languageCode = "zh-tw"
title = "周仲翔的文學空間"
theme = "PaperMod"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "關於作者"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "copyright"
    name = "版權與使用說明"
    url = "/copyright/"
    weight = 2

  [[menu.main]]
    identifier = "changelog"
    name = "更新記錄"
    url = "/changelog/"
    weight = 3